# Generated by Django 5.2.17 on 2026-09-08 16:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('account_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Enter a 12-digit AWS account ID.')])),
                ('role_arn', models.CharField(blank=True, max_length=300)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter currency code.')])),
                ('enabled', models.BooleanField(default=True)),
                ('sync_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syncs', to='billing.customer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('account_id', models.CharField(max_length=12)),
                ('service', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('unblended', models.DecimalField(decimal_places=10, max_digits=24)),
                ('amortized', models.DecimalField(decimal_places=10, max_digits=24)),
                ('estimated', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'currency'], name='billing_cos_day_fede28_idx'), models.Index(fields=['customer', 'day'], name='billing_cos_custome_f469f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'day', 'account_id', 'service', 'currency'), name='unique_cost_slice')],
            },
        ),
    ]
