# Generated by Django 5.2.17 on 2026-09-08 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExplorerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('connection_fingerprint', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, null=True)),
                ('requested', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorer_queries', to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['requested', 'last_used'], name='billing_exp_request_dd4f26_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'fingerprint'), name='unique_explorer_query')],
            },
        ),
    ]
