# Generated by Django 5.2.17 on 2026-09-08 18:33

import billing.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_savedreport_explorerquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(default=datetime.date(2000, 1, 1))),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive; blank means current.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["account__account_id", "start"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("kind", models.CharField(max_length=10)),
                ("threshold", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "value",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                ("message", models.CharField(max_length=300)),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_by", models.CharField(blank=True, max_length=150)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AllocationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accounts", "Linked accounts"),
                            ("tag", "Cost allocation tag"),
                            ("cost_category", "AWS cost category"),
                            ("account_tag", "Accounts + tag"),
                            ("account_category", "Accounts + cost category"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_ids", models.JSONField(blank=True, default=list)),
                ("key", models.CharField(blank=True, max_length=120)),
                ("values", models.JSONField(blank=True, default=list)),
                (
                    "effective_start",
                    models.DateField(default=datetime.date(2000, 1, 1)),
                ),
                ("effective_end", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "pk"],
            },
        ),
        migrations.CreateModel(
            name="AwsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "Enter a 12-digit AWS account ID."
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("state", models.CharField(blank=True, max_length=30)),
                ("payer_account_id", models.CharField(blank=True, max_length=12)),
                ("environment", models.CharField(blank=True, max_length=40)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("missing_since", models.DateTimeField(blank=True, null=True)),
                ("discovery", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["account_id"],
            },
        ),
        migrations.CreateModel(
            name="BillingSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payer", "Management / payer account"),
                            ("standalone", "Standalone account"),
                            (
                                "member_budgets",
                                "Member budget reader (no cost collection)",
                            ),
                        ],
                        default="payer",
                        max_length=20,
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "Enter a 12-digit AWS account ID."
                            )
                        ],
                    ),
                ),
                ("role_arn", models.CharField(blank=True, max_length=300)),
                (
                    "external_id",
                    models.CharField(
                        default=billing.models.new_external_id,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "shared",
                    models.BooleanField(
                        default=False,
                        help_text="Payer serves several customers; accounts need explicit assignment.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("connection_version", models.PositiveIntegerField(default=1)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("discovery_mode", models.CharField(blank=True, max_length=20)),
                ("onboarding_step", models.PositiveSmallIntegerField(default=2)),
                ("sync_requested", models.BooleanField(default=False)),
                ("initial_import_done", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["customer__name", "account_id"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("source", "Payer connection"),
                            ("account", "Linked account"),
                            ("project", "Project"),
                        ],
                        default="customer",
                        max_length=10,
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=12)),
                ("name", models.CharField(max_length=120)),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter currency code."
                            )
                        ],
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("unblended", "Unblended"),
                            ("amortized", "Amortized"),
                        ],
                        default="unblended",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "actual_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80"), max_digits=6
                    ),
                ),
                (
                    "forecast_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=6
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["customer__name", "scope", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("effective_from", models.DateField(default=datetime.date(2000, 1, 1))),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "month",
                    models.DateField(
                        blank=True,
                        help_text="Set for a specific-month override.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-month", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="BudgetEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "actual",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "forecast",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                ("forecast_method", models.CharField(blank=True, max_length=30)),
                ("status", models.CharField(default="Not configured", max_length=30)),
                ("data_status", models.CharField(default="missing", max_length=30)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="BulkImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("uploaded_by", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rows", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("rows", models.PositiveIntegerField(default=0)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("first_day", models.DateField(blank=True, null=True)),
                ("last_day", models.DateField(blank=True, null=True)),
                ("estimated", models.BooleanField(default=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="ImportedBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owning_account_id", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=200)),
                ("arn", models.CharField(blank=True, max_length=400)),
                ("budget_type", models.CharField(max_length=40)),
                ("time_unit", models.CharField(max_length=20)),
                (
                    "limit_amount",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                ("limit_unit", models.CharField(blank=True, max_length=20)),
                ("time_period", models.JSONField(blank=True, default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                ("actual_unit", models.CharField(blank=True, max_length=20)),
                (
                    "forecast_amount",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                ("forecast_unit", models.CharField(blank=True, max_length=20)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("aws_updated_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["owning_account_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("key", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="queued", max_length=10)),
                ("priority", models.PositiveSmallIntegerField(default=5)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_expires", models.DateTimeField(blank=True, null=True)),
                ("worker", models.CharField(blank=True, max_length=80)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=6)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=40)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["customer__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("account_id", models.CharField(max_length=12)),
                ("currency", models.CharField(max_length=10)),
                ("unblended", models.DecimalField(decimal_places=10, max_digits=24)),
                ("amortized", models.DecimalField(decimal_places=10, max_digits=24)),
                ("estimated", models.BooleanField(default=True)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="cost",
            name="unique_cost_slice",
        ),
        migrations.RemoveConstraint(
            model_name="explorerquery",
            name="unique_explorer_query",
        ),
        migrations.AddField(
            model_name="auditevent",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="offboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="owner",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Account owner"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="reference",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Internal reference"
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cost",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="billing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="explorerquery",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explorer_queries",
                to="billing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="syncrun",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="syncs",
                to="billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="accountassignment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="accountassignment",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="billing.awsaccount",
            ),
        ),
        migrations.AddField(
            model_name="billingsource",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="cost",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="explorerquery",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explorer_queries",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="syncs",
                to="billing.billingsource",
            ),
        ),
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["account_id", "day"], name="billing_cos_account_e9b812_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cost",
            constraint=models.UniqueConstraint(
                fields=("source", "day", "account_id", "service", "currency"),
                name="unique_cost_slice",
            ),
        ),
        migrations.AddConstraint(
            model_name="explorerquery",
            constraint=models.UniqueConstraint(
                fields=("source", "fingerprint"), name="unique_explorer_query"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="billing.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetamount",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amounts",
                to="billing.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetevaluation",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="billing.budget",
            ),
        ),
        migrations.AddField(
            model_name="collectionperiod",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="importedbudget",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_budgets",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="billing.billingsource",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="billing.project",
            ),
        ),
        migrations.AddField(
            model_name="allocationrule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="billing.project",
            ),
        ),
        migrations.AddField(
            model_name="projectcost",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="costs",
                to="billing.project",
            ),
        ),
        migrations.AddField(
            model_name="projectcost",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="costs",
                to="billing.allocationrule",
            ),
        ),
        migrations.AddField(
            model_name="projectcost",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_costs",
                to="billing.billingsource",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end__isnull", True),
                    ("end__gt", models.F("start")),
                    _connector="OR",
                ),
                name="assignment_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["payer", "standalone"])),
                fields=("account_id",),
                name="unique_cost_source_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                fields=("budget", "month", "kind", "threshold"), name="unique_alert"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetevaluation",
            constraint=models.UniqueConstraint(
                fields=("budget", "month"), name="unique_budget_evaluation"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionperiod",
            constraint=models.UniqueConstraint(
                fields=("source", "month"), name="unique_collection_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="importedbudget",
            constraint=models.UniqueConstraint(
                fields=("source", "owning_account_id", "name"),
                name="unique_imported_budget",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "run_after", "priority"],
                name="billing_job_status_5da0db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["key"], name="billing_job_key_5f611e_idx"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "leased"])),
                fields=("key",),
                name="unique_active_job_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("customer", "name"), name="unique_project_name"
            ),
        ),
        migrations.AddIndex(
            model_name="projectcost",
            index=models.Index(
                fields=["project", "day"], name="billing_pro_project_c88455_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcost",
            constraint=models.UniqueConstraint(
                fields=("rule", "source", "day", "account_id", "currency"),
                name="unique_project_cost",
            ),
        ),
            # Relax legacy Customer constraints before the data migration so that a reverse
        # migration can re-add nullable columns and 0004 can repopulate them.
        migrations.AlterField(model_name='customer', name='account_id', field=models.CharField(max_length=12, null=True, blank=True)),
        migrations.AlterField(model_name='customer', name='external_id', field=models.UUIDField(null=True, blank=True)),
    ]
