# Generated by Django 5.2.17 on 2026-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_migrate_customer_connections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="enabled",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_attempt",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_error",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_success",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="role_arn",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="sync_requested",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="verified_at",
        ),
    ]
