# Generated by Django 5.2.17 on 2026-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_remove_legacy_customer_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["customer", "currency", "day"],
                name="billing_cost_scope_day_idx",
            ),
        ),
    ]
