# Generated by Django 5.2.17 on 2026-09-09 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_cost_scope_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter currency code.')])),
                ('account_name', models.CharField(blank=True, max_length=200, verbose_name='Account name')),
                ('legal_entity', models.CharField(blank=True, max_length=250, verbose_name='Customer legal entity (as in Partner Central)')),
                ('ace_opportunity_id', models.CharField(blank=True, max_length=100, verbose_name='ACE opportunity ID')),
                ('bill_pulled_on', models.DateField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('shared_with', models.CharField(blank=True, max_length=200, verbose_name='Shared with (Alliance)')),
                ('date_shared', models.DateField(blank=True, null=True)),
                ('apn_marked', models.BooleanField(default=False, verbose_name='APN marked')),
                ('apn_marked_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Notes / blocker')),
                ('blocked', models.BooleanField(default=False, verbose_name='Has an unresolved blocker')),
                ('summary_note', models.TextField(blank=True, max_length=4000, verbose_name='Summary note for alliance team')),
                ('snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alliance_records', to='billing.awsaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alliance_records', to='billing.customer')),
            ],
            options={
                'ordering': ['-month', 'customer__name', 'account__account_id'],
            },
        ),
        migrations.CreateModel(
            name='AllianceServiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('commentary', models.TextField(blank=True, max_length=2000)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notes', to='billing.alliancerecord')),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.AddConstraint(
            model_name='alliancerecord',
            constraint=models.UniqueConstraint(fields=('customer', 'account', 'month', 'currency'), name='unique_alliance_account_month'),
        ),
        migrations.AddConstraint(
            model_name='allianceservicenote',
            constraint=models.UniqueConstraint(fields=('record', 'service'), name='unique_alliance_service_note'),
        ),
    ]
