# Generated by Django 5.2.17 on 2026-09-09 03:52

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alliancerecord_allianceservicenote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsource',
            name='approved_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billingsource',
            name='trust_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='billingsource',
            name='external_id',
            field=models.CharField(default=billing.models.new_external_id, editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='AlertRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='*', max_length=40)),
                ('recipients', models.JSONField(default=list)),
                ('severity', models.CharField(default='warning', max_length=12)),
                ('escalation_minutes', models.PositiveIntegerField(default=60)),
                ('enabled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField(blank=True, default=list)),
                ('authorized_users', models.JSONField(blank=True, default=list)),
                ('expected_accounts', models.JSONField(blank=True, default=list)),
                ('billing_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=list)),
                ('storage_region', models.CharField(blank=True, max_length=30)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('evidence', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowlist_removed_at', models.DateTimeField(blank=True, null=True)),
                ('trust_revocation_reference', models.CharField(blank=True, max_length=500)),
                ('sessions_expire_after', models.DateTimeField()),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('deletion_approved_reference', models.CharField(blank=True, max_length=500)),
                ('deletion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('severity', models.CharField(default='warning', max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('account_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(max_length=150)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(help_text='Inclusive UI end date')),
                ('metric', models.CharField(choices=[('unblended', 'Unblended'), ('amortized', 'Amortized')], max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('scope', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('reference', models.CharField(max_length=500)),
                ('synthetic', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='billing.customer')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.billingsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolloutReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=80)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('security_evidence', models.CharField(blank=True, max_length=500)),
                ('independent_review', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollout', to='billing.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_access', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('oidc_subject', models.CharField(blank=True, max_length=255)),
                ('oidc_issuer', models.URLField(blank=True)),
                ('recovery_hashes', models.JSONField(blank=True, default=list)),
                ('recovery_failed', models.PositiveIntegerField(default=0)),
                ('recovery_locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('viewer', 'Viewer'), ('customer', 'Customer user')], max_length=12)),
                ('account_ids', models.JSONField(blank=True, default=list, help_text='Empty grants the whole customer; otherwise only these assigned accounts.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'customer'), name='unique_customer_membership')],
            },
        ),
        migrations.CreateModel(
            name='RoleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_arn', models.CharField(max_length=300)),
                ('connection_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='requested', max_length=20)),
                ('evidence', models.CharField(blank=True, max_length=500)),
                ('requested_by', models.CharField(max_length=150)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_approvals', to='billing.billingsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'role_arn', 'connection_version'), name='unique_role_approval_version')],
            },
        ),
    ]
