# Generated by Django 5.2.17 on 2026-09-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_customermembership_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsource',
            name='ownership_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
