# Generated by Django 5.2.17 on 2026-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_preserve_saved_report_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapproval',
            name='optional_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
