# Generated by Django 5.2.17 on 2026-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_customerapproval_optional_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerquery',
            name='scope_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
