# Generated by Django 5.2.17 on 2026-09-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_explorerquery_scope_fingerprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingsource',
            options={'ordering': ['account_id']},
        ),
    ]
