# Generated by Django 5.2.17 on 2026-09-09 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_billingsource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('actor', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.JSONField(default=dict)),
                ('fields', models.JSONField(default=dict)),
                ('service_notes', models.JSONField(default=dict)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='billing.alliancerecord')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('record', 'revision'), name='unique_alliance_revision')],
            },
        ),
    ]
