# Generated by Django 5.2.17 on 2026-09-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_preserve_alliance_revision_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinvitation',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usersecurity',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('oidc_issuer', ''), _negated=True), models.Q(('oidc_subject', ''), _negated=True)), fields=('oidc_issuer', 'oidc_subject'), name='unique_oidc_identity'),
        ),
    ]
