# Generated by Django 5.2.17 on 2026-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_portalinvitation_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountassignment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Approved customer-specific alias, owner and environment; retained with this ownership interval.'),
        ),
        migrations.AlterField(
            model_name='billingsource',
            name='role_arn',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='roleapproval',
            name='role_arn',
            field=models.CharField(max_length=2048),
        ),
    ]
