listen_addresses = '*'
ssl = on
ssl_cert_file = '/run/postgres-tls/server.crt'
ssl_key_file = '/run/postgres-tls/server.key'
password_encryption = 'scram-sha-256'
log_statement = 'none'
log_connections = on
log_disconnections = on
